// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/dashboard": {
    params: {};
  };
  "/app/customers": {
    params: {};
  };
  "/app/customers/:id": {
    params: {
      "id": string;
    };
  };
  "/app/customize": {
    params: {};
  };
  "/app/points-rules": {
    params: {};
  };
  "/app/points-rules/order": {
    params: {};
  };
  "/app/points-rules/referral": {
    params: {};
  };
  "/app/points-rules/review": {
    params: {};
  };
  "/app/rewards-rules": {
    params: {};
  };
  "/app/physical-prizes-rules": {
    params: {};
  };
  "/app/physical-prizes-claims-manage": {
    params: {};
  };
  "/app/points-events": {
    params: {};
  };
  "/app/jobs": {
    params: {};
  };
  "/api/claim-prize": {
    params: {};
  };
  "/api/get-reward-voucher": {
    params: {};
  };
  "/api/join-our-program": {
    params: {};
  };
  "/api/get-referral-discount": {
    params: {};
  };
  "/api/loox-new-review-trigger": {
    params: {};
  };
  "/api/provision-customer": {
    params: {};
  };
  "/widget-data": {
    params: {};
  };
  "/widget-data/notifications/mark-seen": {
    params: {};
  };
  "/webhooks/app/orders_paid": {
    params: {};
  };
  "/webhooks/app/orders_cancelled": {
    params: {};
  };
  "/webhooks/app/refunds_create": {
    params: {};
  };
  "/webhooks/app/customers_create": {
    params: {};
  };
  "/webhooks/app/customers_delete": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/auth/login" | "/auth/*" | "/app" | "/app/dashboard" | "/app/customers" | "/app/customers/:id" | "/app/customize" | "/app/points-rules" | "/app/points-rules/order" | "/app/points-rules/referral" | "/app/points-rules/review" | "/app/rewards-rules" | "/app/physical-prizes-rules" | "/app/physical-prizes-claims-manage" | "/app/points-events" | "/app/jobs" | "/api/claim-prize" | "/api/get-reward-voucher" | "/api/join-our-program" | "/api/get-referral-discount" | "/api/loox-new-review-trigger" | "/api/provision-customer" | "/widget-data" | "/widget-data/notifications/mark-seen" | "/webhooks/app/orders_paid" | "/webhooks/app/orders_cancelled" | "/webhooks/app/refunds_create" | "/webhooks/app/customers_create" | "/webhooks/app/customers_delete" | "/webhooks/app/uninstalled" | "/webhooks/app/scopes_update";
  };
  "routes/auth.login/route.jsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/_index/route.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.jsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/app.jsx": {
    id: "routes/app";
    page: "/app";
  };
  "routes/app._index.jsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "./layout/index.jsx": {
    id: "layout/index";
    page: "/app/dashboard" | "/app/customers" | "/app/customers/:id" | "/app/customize" | "/app/points-rules" | "/app/points-rules/order" | "/app/points-rules/referral" | "/app/points-rules/review" | "/app/rewards-rules" | "/app/physical-prizes-rules" | "/app/physical-prizes-claims-manage" | "/app/points-events" | "/app/jobs";
  };
  "./layout/dashboard/route.jsx": {
    id: "layout/dashboard/route";
    page: "/app/dashboard";
  };
  "./layout/customers/index/route.jsx": {
    id: "layout/customers/index/route";
    page: "/app/customers";
  };
  "./layout/customers/$id/route.jsx": {
    id: "layout/customers/$id/route";
    page: "/app/customers/:id";
  };
  "./layout/customize/route.jsx": {
    id: "layout/customize/route";
    page: "/app/customize";
  };
  "./layout/points-rules/index/route.jsx": {
    id: "layout/points-rules/index/route";
    page: "/app/points-rules";
  };
  "./layout/points-rules/order/route.jsx": {
    id: "layout/points-rules/order/route";
    page: "/app/points-rules/order";
  };
  "./layout/points-rules/referral/route.jsx": {
    id: "layout/points-rules/referral/route";
    page: "/app/points-rules/referral";
  };
  "./layout/points-rules/review/route.jsx": {
    id: "layout/points-rules/review/route";
    page: "/app/points-rules/review";
  };
  "./layout/rewards-rules/route.jsx": {
    id: "layout/rewards-rules/route";
    page: "/app/rewards-rules";
  };
  "./layout/physical-prizes-rules/route.jsx": {
    id: "layout/physical-prizes-rules/route";
    page: "/app/physical-prizes-rules";
  };
  "./layout/physical-prizes-claims-manage/route.jsx": {
    id: "layout/physical-prizes-claims-manage/route";
    page: "/app/physical-prizes-claims-manage";
  };
  "./layout/points-events/route.jsx": {
    id: "layout/points-events/route";
    page: "/app/points-events";
  };
  "./layout/jobs/route.jsx": {
    id: "layout/jobs/route";
    page: "/app/jobs";
  };
  "./api-routes/physical-prize-claim.jsx": {
    id: "api-routes/physical-prize-claim";
    page: "/api/claim-prize";
  };
  "./api-routes/reward-claim.jsx": {
    id: "api-routes/reward-claim";
    page: "/api/get-reward-voucher";
  };
  "./api-routes/join-our-program.jsx": {
    id: "api-routes/join-our-program";
    page: "/api/join-our-program";
  };
  "./api-routes/referral-claim.jsx": {
    id: "api-routes/referral-claim";
    page: "/api/get-referral-discount";
  };
  "./api-routes/loox-new-review-trigger.jsx": {
    id: "api-routes/loox-new-review-trigger";
    page: "/api/loox-new-review-trigger";
  };
  "./api-routes/provision-customer.jsx": {
    id: "api-routes/provision-customer";
    page: "/api/provision-customer";
  };
  "./widget-ui/route.jsx": {
    id: "widget-ui/route";
    page: "/widget-data";
  };
  "./widget-ui/notifications-mark-seen.jsx": {
    id: "widget-ui/notifications-mark-seen";
    page: "/widget-data/notifications/mark-seen";
  };
  "./webhook-routes/order-paid.jsx": {
    id: "webhook-routes/order-paid";
    page: "/webhooks/app/orders_paid";
  };
  "./webhook-routes/order-cancelled.jsx": {
    id: "webhook-routes/order-cancelled";
    page: "/webhooks/app/orders_cancelled";
  };
  "./webhook-routes/refund-created.jsx": {
    id: "webhook-routes/refund-created";
    page: "/webhooks/app/refunds_create";
  };
  "./webhook-routes/customer-create.jsx": {
    id: "webhook-routes/customer-create";
    page: "/webhooks/app/customers_create";
  };
  "./webhook-routes/customer-delete.jsx": {
    id: "webhook-routes/customer-delete";
    page: "/webhooks/app/customers_delete";
  };
  "./webhook-routes/app-uninstalled.jsx": {
    id: "webhook-routes/app-uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "./webhook-routes/scopes-update.jsx": {
    id: "webhook-routes/scopes-update";
    page: "/webhooks/app/scopes_update";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.jsx");
  "routes/_index": typeof import("./app/routes/_index/route.jsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.jsx");
  "routes/app": typeof import("./app/routes/app.jsx");
  "routes/app._index": typeof import("./app/routes/app._index.jsx");
  "layout/index": typeof import("./app/./layout/index.jsx");
  "layout/dashboard/route": typeof import("./app/./layout/dashboard/route.jsx");
  "layout/customers/index/route": typeof import("./app/./layout/customers/index/route.jsx");
  "layout/customers/$id/route": typeof import("./app/./layout/customers/$id/route.jsx");
  "layout/customize/route": typeof import("./app/./layout/customize/route.jsx");
  "layout/points-rules/index/route": typeof import("./app/./layout/points-rules/index/route.jsx");
  "layout/points-rules/order/route": typeof import("./app/./layout/points-rules/order/route.jsx");
  "layout/points-rules/referral/route": typeof import("./app/./layout/points-rules/referral/route.jsx");
  "layout/points-rules/review/route": typeof import("./app/./layout/points-rules/review/route.jsx");
  "layout/rewards-rules/route": typeof import("./app/./layout/rewards-rules/route.jsx");
  "layout/physical-prizes-rules/route": typeof import("./app/./layout/physical-prizes-rules/route.jsx");
  "layout/physical-prizes-claims-manage/route": typeof import("./app/./layout/physical-prizes-claims-manage/route.jsx");
  "layout/points-events/route": typeof import("./app/./layout/points-events/route.jsx");
  "layout/jobs/route": typeof import("./app/./layout/jobs/route.jsx");
  "api-routes/physical-prize-claim": typeof import("./app/./api-routes/physical-prize-claim.jsx");
  "api-routes/reward-claim": typeof import("./app/./api-routes/reward-claim.jsx");
  "api-routes/join-our-program": typeof import("./app/./api-routes/join-our-program.jsx");
  "api-routes/referral-claim": typeof import("./app/./api-routes/referral-claim.jsx");
  "api-routes/loox-new-review-trigger": typeof import("./app/./api-routes/loox-new-review-trigger.jsx");
  "api-routes/provision-customer": typeof import("./app/./api-routes/provision-customer.jsx");
  "widget-ui/route": typeof import("./app/./widget-ui/route.jsx");
  "widget-ui/notifications-mark-seen": typeof import("./app/./widget-ui/notifications-mark-seen.jsx");
  "webhook-routes/order-paid": typeof import("./app/./webhook-routes/order-paid.jsx");
  "webhook-routes/order-cancelled": typeof import("./app/./webhook-routes/order-cancelled.jsx");
  "webhook-routes/refund-created": typeof import("./app/./webhook-routes/refund-created.jsx");
  "webhook-routes/customer-create": typeof import("./app/./webhook-routes/customer-create.jsx");
  "webhook-routes/customer-delete": typeof import("./app/./webhook-routes/customer-delete.jsx");
  "webhook-routes/app-uninstalled": typeof import("./app/./webhook-routes/app-uninstalled.jsx");
  "webhook-routes/scopes-update": typeof import("./app/./webhook-routes/scopes-update.jsx");
};